# Generated by Django 3.2.6 on 2023-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docno', models.CharField(max_length=255, unique=True)),
                ('site', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('ingredients', models.JSONField(default=list)),
                ('allergens', models.JSONField(default=list)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
