# Generated by Django 4.2.7 on 2023-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chocoFinder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chocolate",
            name="image",
            field=models.CharField(default=list, max_length=255),
        ),
    ]
